### ISSUE TITLE
New release wanted for PluginRegistry (and PluggableAuthService)

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Products.PluginRegistry#1]
Can we have a new release of Products.PluginRegistry? There is a fix for Windows.

And also Products.PluggableAuthService, please. It has the same fix, plus a small enhancement I just merged.

For both packages, pinging @tseaver and @dataflake.
PluggableAuthService could also be done by @icemac.
Thanks!

**Comment by icemac** [comment]
@mauritsvanrees I made a release of Products.PluggableAuthService as version 1.11.0

**Comment by mauritsvanrees** [comment]
Thank you!

**Comment by tseaver** [comment]
https://pypi.python.org/pypi/Products.PluginRegistry/1.4

**Comment by mauritsvanrees** [comment]
And thank you,Tres!
