### ISSUE TITLE
New release for Products.PluginRegistry

### ISSUE THREAD

**Issue by esteele** [zopefoundation/Products.PluginRegistry#10]
@tseaver, @dataflake Could we have a 1.7 release to include the latest Python 3 fixes?

**Comment by pbauer** [comment]
maybe @icemac has time to do the release?

**Comment by icemac** [comment]
I do not have the necessary PyPI rights. But I can cut a release once I (`icemac`) get the necessary rights.

**Comment by dataflake** [comment]
You're co-owner now

**Comment by icemac** [comment]
@dataflake Thank you, I'm going to cut a release now.

**Comment by icemac** [comment]
Released https://pypi.org/project/Products.PluginRegistry/1.6.1/
